// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalCabinetEducationProgram.Data;

#nullable disable

namespace PersonalCabinetEducationProgram.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260813161105_AddIpAccountRiskEscalation")]
    partial class AddIpAccountRiskEscalation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_rc_role");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_uc_user");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ul_user");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_ur_role");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.ApproverAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("int")
                        .HasColumnName("approver_user_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId")
                        .HasDatabaseName("ix_appr_user");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_appr_by");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_appr_dept");

                    b.HasIndex("FacultyId")
                        .HasDatabaseName("ix_appr_fac");

                    b.ToTable("approver_assignments", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("details");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext")
                        .HasColumnName("new_values");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("longtext")
                        .HasColumnName("previous_values");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("user_full_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_login");

                    b.Property<string>("UserRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_role");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_created");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_user");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entity");

                    b.ToTable("audit_log", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.CurriculumImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArchivedCount")
                        .HasColumnType("int")
                        .HasColumnName("archived_count");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("int")
                        .HasColumnName("created_count");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("imported_at");

                    b.Property<int>("ImportedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("imported_by_user_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("plan_code");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("plan_name");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int")
                        .HasColumnName("skipped_count");

                    b.Property<string>("SourceAppVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_app_version");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("stored_file_path");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int")
                        .HasColumnName("updated_count");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("warnings_json");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramId")
                        .HasDatabaseName("ix_curriculum_import_program");

                    b.HasIndex("ImportedAt")
                        .HasDatabaseName("ix_curriculum_import_date");

                    b.HasIndex("ImportedByUserId")
                        .HasDatabaseName("ix_curriculum_import_user");

                    b.ToTable("curriculum_imports", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeDepartment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code_department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("departments", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeDepartment = "Каф.ПМИ",
                            Name = "Кафедра прикладной математики и информатики"
                        },
                        new
                        {
                            Id = 2,
                            CodeDepartment = "Каф.ИВТ",
                            Name = "Кафедра информационных вычислительных технологий"
                        },
                        new
                        {
                            Id = 3,
                            CodeDepartment = "Каф.МАТЕМ",
                            Name = "Кафедра математического анализа"
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("archived_at");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("archived_by_user_id");

                    b.Property<string>("CodeReferral")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code_referral");

                    b.Property<string>("EducationalLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("educational_level");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<int?>("YearApprovals")
                        .HasColumnType("int")
                        .HasColumnName("year_approvals");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_prog_archived");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_prog_user");

                    b.ToTable("educational_programs", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeReferral = "01.03.02",
                            EducationalLevel = "Бакалавриат",
                            IsArchived = false,
                            Name = "Прикладная математика и информатика",
                            Status = "Разрабатывается",
                            UserId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            CodeReferral = "09.03.01",
                            EducationalLevel = "Бакалавриат",
                            IsArchived = false,
                            Name = "Информатика и вычислительная техника",
                            Status = "Разрабатывается",
                            UserId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            CodeReferral = "44.03.05",
                            EducationalLevel = "Бакалавриат",
                            IsArchived = false,
                            Name = "Педагогическое образование (Математика. Информатика)",
                            Status = "Разрабатывается",
                            UserId = 1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_id");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_epa_dept");

                    b.HasIndex("EducationalProgramId")
                        .HasDatabaseName("ix_epa_prog");

                    b.HasIndex("FacultyId")
                        .HasDatabaseName("ix_epa_fac");

                    b.HasIndex("EducationalProgramId", "DepartmentId", "FacultyId")
                        .IsUnique()
                        .HasDatabaseName("ux_epa_program_department_faculty");

                    b.ToTable("educational_program_assignments", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            EducationalProgramId = 1,
                            FacultyId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            EducationalProgramId = 2,
                            FacultyId = 1
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            EducationalProgramId = 3,
                            FacultyId = 3
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("archived_at");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("archived_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_id");

                    b.Property<string>("ExternalKey")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("external_key");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("external_source");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastImportedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_imported_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParentExternalKey")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("parent_external_key");

                    b.Property<string>("StatusApprovals")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_approvals");

                    b.Property<string>("TypeElement")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_element");

                    b.Property<DateOnly?>("UploadDate")
                        .HasColumnType("date")
                        .HasColumnName("upload_date");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramId")
                        .HasDatabaseName("ix_elem_prog");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_elem_archived");

                    b.HasIndex("EducationalProgramId", "ExternalSource", "ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ux_elem_external_key");

                    b.ToTable("educational_program_elements", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Основной учебный план",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Учебный план (очный)",
                            StatusApprovals = "",
                            TypeElement = "Main",
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Общая информация",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Пояснительная записка",
                            StatusApprovals = "На доработку",
                            TypeElement = "Main",
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "График обучения",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Календарный учебный график",
                            StatusApprovals = "",
                            TypeElement = "Main",
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Воспитательная программа",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Программа воспитательной работы",
                            StatusApprovals = "",
                            TypeElement = "Main",
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Календарный план",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Календарный план воспитательной работы",
                            StatusApprovals = "",
                            TypeElement = "Main",
                            Version = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Б1.О.01",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Философия",
                            StatusApprovals = "Согласовано",
                            TypeElement = "Discipline",
                            Version = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Б1.О.02",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Математический анализ",
                            StatusApprovals = "На согласовании",
                            TypeElement = "Discipline",
                            Version = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Б1.О.03",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Линейная алгебра",
                            StatusApprovals = "",
                            TypeElement = "Discipline",
                            Version = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Б1.О.04",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Программирование",
                            StatusApprovals = "Согласовано",
                            TypeElement = "Discipline",
                            Version = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Б1.О.05",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Базы данных",
                            StatusApprovals = "",
                            TypeElement = "Discipline",
                            Version = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Практика 1",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Учебная практика",
                            StatusApprovals = "",
                            TypeElement = "Practice",
                            Version = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Практика 2",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Производственная практика",
                            StatusApprovals = "",
                            TypeElement = "Practice",
                            Version = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "ГИА",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Государственный экзамен",
                            StatusApprovals = "",
                            TypeElement = "GIA",
                            Version = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "ВКР",
                            EducationalProgramId = 1,
                            IsArchived = false,
                            Name = "Выпускная квалификационная работа",
                            StatusApprovals = "",
                            TypeElement = "GIA",
                            Version = 1
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElementComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comment_content");

                    b.Property<DateTime>("DateTimeComment")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_time_comment");

                    b.Property<int>("EducationalProgramElementId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_element_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramElementId")
                        .HasDatabaseName("ix_comm_elem");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comm_user");

                    b.ToTable("comments_educational_program_element", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElementFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EducationalProgramElementId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_element_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_current");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_removed");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_submitted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("original_file_name");

                    b.Property<string>("RemovalReason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("removal_reason");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("removed_at");

                    b.Property<int?>("RemovedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("removed_by_user_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int")
                        .HasColumnName("revision_number");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramElementId")
                        .HasDatabaseName("ix_elem_file_element");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("EducationalProgramElementId", "RevisionNumber")
                        .HasDatabaseName("ix_elem_file_revision");

                    b.ToTable("educational_program_element_files", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_mgr_by");

                    b.HasIndex("EducationalProgramId")
                        .HasDatabaseName("ix_mgr_prog");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mgr_user");

                    b.ToTable("educational_program_managers", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2026, 5, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedByUserId = 4,
                            EducationalProgramId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2026, 5, 30, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            AssignedByUserId = 4,
                            EducationalProgramId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2026, 5, 30, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            AssignedByUserId = 4,
                            EducationalProgramId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.ElementStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("change_date");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<int>("EducationalProgramElementId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_element_id");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("old_status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramElementId")
                        .HasDatabaseName("ix_hist_elem");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hist_user");

                    b.ToTable("element_status_history", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.Facultys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("facultys", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Факультет информационных технологий"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Факультет математики и механики"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Факультет педагогического образования"
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.IpAddressSecurityState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AccountRiskEscalationLevel")
                        .HasColumnType("int")
                        .HasColumnName("account_risk_escalation_level");

                    b.Property<DateTime?>("AccountRiskLastBlockedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("account_risk_last_blocked_at_utc");

                    b.Property<DateTime?>("AccountRiskMarkedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("account_risk_marked_at_utc");

                    b.Property<int>("AccountRiskScore")
                        .HasColumnType("int")
                        .HasColumnName("account_risk_score");

                    b.Property<DateTime?>("AccountRiskWindowResetAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("account_risk_window_reset_at_utc");

                    b.Property<DateTime?>("AttemptWindowStartedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("attempt_window_started_at_utc");

                    b.Property<int>("AttemptsInWindow")
                        .HasColumnType("int")
                        .HasColumnName("attempts_in_window");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("block_reason");

                    b.Property<DateTime?>("BlockedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("blocked_at_utc");

                    b.Property<int?>("BlockedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("blocked_by_user_id");

                    b.Property<DateTime?>("BlockedUntilUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("blocked_until_utc");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("int")
                        .HasColumnName("escalation_level");

                    b.Property<DateTime?>("EscalationStartedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("escalation_started_at_utc");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsManuallyBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_manually_blocked");

                    b.Property<bool>("IsPermanentlyBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_permanently_blocked");

                    b.Property<string>("LastHttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("last_http_method");

                    b.Property<string>("LastPath")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("last_path");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("LastUserFullName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("last_user_full_name");

                    b.Property<int?>("LastUserId")
                        .HasColumnType("int")
                        .HasColumnName("last_user_id");

                    b.Property<string>("LastUserLogin")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("last_user_login");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint")
                        .HasColumnName("request_count");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("review_note");

                    b.Property<int>("SuspiciousAttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("suspicious_attempt_count");

                    b.Property<DateTime?>("UnblockedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("unblocked_at_utc");

                    b.Property<int?>("UnblockedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("unblocked_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_ip_security_address");

                    b.HasIndex("LastSeenAtUtc")
                        .HasDatabaseName("ix_ip_security_last_seen");

                    b.HasIndex("EscalationLevel", "LastSeenAtUtc")
                        .HasDatabaseName("ix_ip_security_escalation");

                    b.HasIndex("IsPermanentlyBlocked", "BlockedUntilUtc")
                        .HasDatabaseName("ix_ip_security_blocked");

                    b.ToTable("ip_address_security_states", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("actor_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("EducationalProgramElementId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_element_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramElementId")
                        .HasDatabaseName("ix_notif_elem");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notif_user");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notif_unread");

                    b.ToTable("notifications", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "role-manager",
                            Description = "Руководитель ОПОП",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "role-approver",
                            Description = "Согласующий",
                            Name = "Approver",
                            NormalizedName = "APPROVER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "role-moderator",
                            Description = "Модератор",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "role-admin",
                            Description = "Администратор",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.SecurityEventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("country_name");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("FirstOccurredAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_occurred_at_utc");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("http_method");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastOccurredAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_occurred_at_utc");

                    b.Property<string>("NetworkAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("network_address");

                    b.Property<int?>("NetworkPrefixLength")
                        .HasColumnType("int")
                        .HasColumnName("network_prefix_length");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("int")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("Path")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("path");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("title");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("user_full_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_login");

                    b.HasKey("Id");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_security_trace");

                    b.HasIndex("IpAddress", "LastOccurredAtUtc")
                        .HasDatabaseName("ix_security_ip_date");

                    b.HasIndex("Severity", "LastOccurredAtUtc")
                        .HasDatabaseName("ix_security_severity_date");

                    b.HasIndex("Status", "LastOccurredAtUtc")
                        .HasDatabaseName("ix_security_status_date");

                    b.HasIndex("UserId", "LastOccurredAtUtc")
                        .HasDatabaseName("ix_security_user_date");

                    b.HasIndex("NetworkAddress", "NetworkPrefixLength", "LastOccurredAtUtc")
                        .HasDatabaseName("ix_security_network_date");

                    b.ToTable("security_event_logs", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.SystemRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<string>("Controller")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("controller");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("error_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("http_method");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("path");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("query_string");

                    b.Property<long?>("RequestSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("request_size_bytes");

                    b.Property<long?>("ResponseSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("response_size_bytes");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("result");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("user_full_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_login");

                    b.Property<string>("UserRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_role");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_request_created");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_request_trace");

                    b.HasIndex("IpAddress", "OccurredAtUtc")
                        .HasDatabaseName("ix_request_ip_created");

                    b.HasIndex("StatusCode", "OccurredAtUtc")
                        .HasDatabaseName("ix_request_status_created");

                    b.HasIndex("UserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_request_user_created");

                    b.ToTable("system_request_logs", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("approval_status");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<int>("ConsecutiveInvalidUploadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_invalid_upload_count");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_confirmed");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("post");

                    b.Property<string>("PreferredTheme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("light")
                        .HasColumnName("preferred_theme");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SecurityBlockReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("security_block_reason");

                    b.Property<DateTime?>("SecurityBlockedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("security_blocked_at_utc");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_name");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ApprovalStatus = "Approved",
                            ConcurrencyStamp = "user-1",
                            ConsecutiveInvalidUploadCount = 0,
                            EmailConfirmed = false,
                            FullName = "Иванов Иван Иванович",
                            LockoutEnabled = true,
                            NormalizedUserName = "MANAGER",
                            PasswordHash = "866485796cfa8d7c0cf7111640205b83076433547577511d81f8030ae99ecea5",
                            PhoneNumberConfirmed = false,
                            Post = "Заведующий кафедрой",
                            PreferredTheme = "light",
                            SecurityStamp = "security-1",
                            TwoFactorEnabled = false,
                            UserName = "manager"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ApprovalStatus = "Approved",
                            ConcurrencyStamp = "user-2",
                            ConsecutiveInvalidUploadCount = 0,
                            EmailConfirmed = false,
                            FullName = "Петрова Анна Сергеевна",
                            LockoutEnabled = true,
                            NormalizedUserName = "APPROVER",
                            PasswordHash = "1c391319644c0c6e9f5955e44e55862a8fd27b3b9d9863456500096ccf512db3",
                            PhoneNumberConfirmed = false,
                            Post = "Декан факультета",
                            PreferredTheme = "light",
                            SecurityStamp = "security-2",
                            TwoFactorEnabled = false,
                            UserName = "approver"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ApprovalStatus = "Approved",
                            ConcurrencyStamp = "user-3",
                            ConsecutiveInvalidUploadCount = 0,
                            EmailConfirmed = false,
                            FullName = "Сидоров Петр Алексеевич",
                            LockoutEnabled = true,
                            NormalizedUserName = "MODERATOR",
                            PasswordHash = "4c8425b174053ea6935b29c2b0e0aa4e2eab1a01b784e6ac91b8bdce9c26235a",
                            PhoneNumberConfirmed = false,
                            Post = "Модератор",
                            PreferredTheme = "light",
                            SecurityStamp = "security-3",
                            TwoFactorEnabled = false,
                            UserName = "moderator"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ApprovalStatus = "Approved",
                            ConcurrencyStamp = "user-4",
                            ConsecutiveInvalidUploadCount = 0,
                            EmailConfirmed = false,
                            FullName = "Козлова Мария Ивановна",
                            LockoutEnabled = true,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            PhoneNumberConfirmed = false,
                            Post = "Администратор",
                            PreferredTheme = "light",
                            SecurityStamp = "security-4",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.UserLoginLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("country_name");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_local");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_trusted");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("NetworkAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("network_address");

                    b.Property<int>("NetworkPrefixLength")
                        .HasColumnType("int")
                        .HasColumnName("network_prefix_length");

                    b.Property<int>("SuccessfulLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("successful_login_count");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_login_location_country");

                    b.HasIndex("LastSeenAtUtc")
                        .HasDatabaseName("ix_login_location_last_seen");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_location_user");

                    b.HasIndex("UserId", "NetworkAddress", "NetworkPrefixLength")
                        .IsUnique()
                        .HasDatabaseName("ux_login_location_user_network");

                    b.ToTable("user_login_locations", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.UserLoginSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_local");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<string>("NetworkAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("network_address");

                    b.Property<int>("NetworkPrefixLength")
                        .HasColumnType("int")
                        .HasColumnName("network_prefix_length");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("session_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_login_session_id");

                    b.HasIndex("UserId", "IsActive", "LastActivityAtUtc")
                        .HasDatabaseName("ix_login_session_user_active");

                    b.ToTable("user_login_sessions", "personal_cabinet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rc_role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uc_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ul_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ur_role");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ur_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ut_user");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.ApproverAssignment", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "ApproverUser")
                        .WithMany("ApproverAssignments")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appr_user");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appr_by");

                    b.HasOne("PersonalCabinetEducationProgram.Models.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_appr_dept");

                    b.HasOne("PersonalCabinetEducationProgram.Models.Facultys", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_appr_fac");

                    b.Navigation("ApproverUser");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Department");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.CurriculumImport", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("CurriculumImports")
                        .HasForeignKey("EducationalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_curriculum_import_program");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "ImportedByUser")
                        .WithMany("CurriculumImports")
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curriculum_import_user");

                    b.Navigation("EducationalProgram");

                    b.Navigation("ImportedByUser");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgram", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("EducationalPrograms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_prog_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramAssignment", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epa_dept");

                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("Assignments")
                        .HasForeignKey("EducationalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epa_prog");

                    b.HasOne("PersonalCabinetEducationProgram.Models.Facultys", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epa_fac");

                    b.Navigation("Department");

                    b.Navigation("EducationalProgram");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElement", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("Elements")
                        .HasForeignKey("EducationalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_elem_prog");

                    b.Navigation("EducationalProgram");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElementComment", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgramElement", "Element")
                        .WithMany("Comments")
                        .HasForeignKey("EducationalProgramElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comm_elem");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comm_user");

                    b.Navigation("Element");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElementFile", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgramElement", "Element")
                        .WithMany("Files")
                        .HasForeignKey("EducationalProgramElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_elem_file_element");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "UploadedByUser")
                        .WithMany("UploadedElementFiles")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_elem_file_user");

                    b.Navigation("Element");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramManager", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mgr_by");

                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("Managers")
                        .HasForeignKey("EducationalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mgr_prog");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("EducationalProgramManagers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mgr_user");

                    b.Navigation("AssignedByUser");

                    b.Navigation("EducationalProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.ElementStatusHistory", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgramElement", "Element")
                        .WithMany()
                        .HasForeignKey("EducationalProgramElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hist_elem");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hist_user");

                    b.Navigation("Element");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.Notification", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgramElement", "Element")
                        .WithMany("Notifications")
                        .HasForeignKey("EducationalProgramElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notif_elem");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notif_user");

                    b.Navigation("Element");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.UserLoginLocation", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("LoginLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_location_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.UserLoginSession", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("LoginSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_session_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgram", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CurriculumImports");

                    b.Navigation("Elements");

                    b.Navigation("Managers");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElement", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Files");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.User", b =>
                {
                    b.Navigation("ApproverAssignments");

                    b.Navigation("Comments");

                    b.Navigation("CurriculumImports");

                    b.Navigation("EducationalProgramManagers");

                    b.Navigation("EducationalPrograms");

                    b.Navigation("LoginLocations");

                    b.Navigation("LoginSessions");

                    b.Navigation("Notifications");

                    b.Navigation("UploadedElementFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
