// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalCabinetEducationProgram.Data;

#nullable disable

namespace PersonalCabinetEducationProgram.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619134645_AddHistoryFileVersions")]
    partial class AddHistoryFileVersions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_rc_role");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_uc_user");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ul_user");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_ur_role");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.ApproverAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("int")
                        .HasColumnName("approver_user_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId")
                        .HasDatabaseName("ix_appr_user");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_appr_by");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_appr_dept");

                    b.HasIndex("FacultyId")
                        .HasDatabaseName("ix_appr_fac");

                    b.ToTable("approver_assignments", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeDepartment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code_department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("departments", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeDepartment = "Каф.ПМИ",
                            Name = "Кафедра прикладной математики и информатики"
                        },
                        new
                        {
                            Id = 2,
                            CodeDepartment = "Каф.ИВТ",
                            Name = "Кафедра информационных вычислительных технологий"
                        },
                        new
                        {
                            Id = 3,
                            CodeDepartment = "Каф.МАТЕМ",
                            Name = "Кафедра математического анализа"
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeReferral")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code_referral");

                    b.Property<string>("EducationalLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("educational_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("YearApprovals")
                        .HasColumnType("int")
                        .HasColumnName("year_approvals");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_prog_user");

                    b.ToTable("educational_programs", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeReferral = "01.03.02",
                            EducationalLevel = "Бакалавриат",
                            Name = "Прикладная математика и информатика",
                            Status = "Разрабатывается",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CodeReferral = "09.03.01",
                            EducationalLevel = "Бакалавриат",
                            Name = "Информатика и вычислительная техника",
                            Status = "Разрабатывается",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CodeReferral = "44.03.05",
                            EducationalLevel = "Бакалавриат",
                            Name = "Педагогическое образование (Математика. Информатика)",
                            Status = "Разрабатывается",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_id");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_epa_dept");

                    b.HasIndex("EducationalProgramId")
                        .HasDatabaseName("ix_epa_prog");

                    b.HasIndex("FacultyId")
                        .HasDatabaseName("ix_epa_fac");

                    b.ToTable("educational_program_assignments", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            EducationalProgramId = 1,
                            FacultyId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            EducationalProgramId = 2,
                            FacultyId = 1
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            EducationalProgramId = 3,
                            FacultyId = 3
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_id");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusApprovals")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_approvals");

                    b.Property<string>("TypeElement")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_element");

                    b.Property<DateOnly?>("UploadDate")
                        .HasColumnType("date")
                        .HasColumnName("upload_date");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramId")
                        .HasDatabaseName("ix_elem_prog");

                    b.ToTable("educational_program_elements", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Основной учебный план",
                            EducationalProgramId = 1,
                            Name = "Учебный план (очный)",
                            StatusApprovals = "",
                            TypeElement = "Main"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Общая информация",
                            EducationalProgramId = 1,
                            Name = "Пояснительная записка",
                            StatusApprovals = "На доработку",
                            TypeElement = "Main"
                        },
                        new
                        {
                            Id = 3,
                            Description = "График обучения",
                            EducationalProgramId = 1,
                            Name = "Календарный учебный график",
                            StatusApprovals = "",
                            TypeElement = "Main"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Воспитательная программа",
                            EducationalProgramId = 1,
                            Name = "Программа воспитательной работы",
                            StatusApprovals = "",
                            TypeElement = "Main"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Календарный план",
                            EducationalProgramId = 1,
                            Name = "Календарный план воспитательной работы",
                            StatusApprovals = "",
                            TypeElement = "Main"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Б1.О.01",
                            EducationalProgramId = 1,
                            Name = "Философия",
                            StatusApprovals = "Согласовано",
                            TypeElement = "Discipline"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Б1.О.02",
                            EducationalProgramId = 1,
                            Name = "Математический анализ",
                            StatusApprovals = "На согласовании",
                            TypeElement = "Discipline"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Б1.О.03",
                            EducationalProgramId = 1,
                            Name = "Линейная алгебра",
                            StatusApprovals = "",
                            TypeElement = "Discipline"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Б1.О.04",
                            EducationalProgramId = 1,
                            Name = "Программирование",
                            StatusApprovals = "Согласовано",
                            TypeElement = "Discipline"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Б1.О.05",
                            EducationalProgramId = 1,
                            Name = "Базы данных",
                            StatusApprovals = "",
                            TypeElement = "Discipline"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Практика 1",
                            EducationalProgramId = 1,
                            Name = "Учебная практика",
                            StatusApprovals = "",
                            TypeElement = "Practice"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Практика 2",
                            EducationalProgramId = 1,
                            Name = "Производственная практика",
                            StatusApprovals = "",
                            TypeElement = "Practice"
                        },
                        new
                        {
                            Id = 13,
                            Description = "ГИА",
                            EducationalProgramId = 1,
                            Name = "Государственный экзамен",
                            StatusApprovals = "",
                            TypeElement = "GIA"
                        },
                        new
                        {
                            Id = 14,
                            Description = "ВКР",
                            EducationalProgramId = 1,
                            Name = "Выпускная квалификационная работа",
                            StatusApprovals = "",
                            TypeElement = "GIA"
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElementComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comment_content");

                    b.Property<DateTime>("DateTimeComment")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_time_comment");

                    b.Property<int>("EducationalProgramElementId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_element_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramElementId")
                        .HasDatabaseName("ix_comm_elem");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comm_user");

                    b.ToTable("comments_educational_program_element", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<int>("EducationalProgramId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_mgr_by");

                    b.HasIndex("EducationalProgramId")
                        .HasDatabaseName("ix_mgr_prog");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mgr_user");

                    b.ToTable("educational_program_managers", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2026, 5, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedByUserId = 4,
                            EducationalProgramId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2026, 5, 30, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            AssignedByUserId = 4,
                            EducationalProgramId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2026, 5, 30, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            AssignedByUserId = 4,
                            EducationalProgramId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.ElementStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("change_date");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<int>("EducationalProgramElementId")
                        .HasColumnType("int")
                        .HasColumnName("educational_program_element_id");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("old_status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EducationalProgramElementId")
                        .HasDatabaseName("ix_hist_elem");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hist_user");

                    b.ToTable("element_status_history", "personal_cabinet");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.Facultys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("facultys", "personal_cabinet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Факультет информационных технологий"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Факультет математики и механики"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Факультет педагогического образования"
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "role-manager",
                            Description = "Руководитель ОПОП",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "role-approver",
                            Description = "Согласующий",
                            Name = "Approver",
                            NormalizedName = "APPROVER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "role-moderator",
                            Description = "Модератор",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "role-admin",
                            Description = "Администратор",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("approval_status");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_confirmed");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("post");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_name");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ApprovalStatus = "Approved",
                            ConcurrencyStamp = "user-1",
                            EmailConfirmed = false,
                            FullName = "Иванов Иван Иванович",
                            LockoutEnabled = true,
                            NormalizedUserName = "MANAGER",
                            PasswordHash = "866485796cfa8d7c0cf7111640205b83076433547577511d81f8030ae99ecea5",
                            PhoneNumberConfirmed = false,
                            Post = "Заведующий кафедрой",
                            SecurityStamp = "security-1",
                            TwoFactorEnabled = false,
                            UserName = "manager"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ApprovalStatus = "Approved",
                            ConcurrencyStamp = "user-2",
                            EmailConfirmed = false,
                            FullName = "Петрова Анна Сергеевна",
                            LockoutEnabled = true,
                            NormalizedUserName = "APPROVER",
                            PasswordHash = "1c391319644c0c6e9f5955e44e55862a8fd27b3b9d9863456500096ccf512db3",
                            PhoneNumberConfirmed = false,
                            Post = "Декан факультета",
                            SecurityStamp = "security-2",
                            TwoFactorEnabled = false,
                            UserName = "approver"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ApprovalStatus = "Approved",
                            ConcurrencyStamp = "user-3",
                            EmailConfirmed = false,
                            FullName = "Сидоров Петр Алексеевич",
                            LockoutEnabled = true,
                            NormalizedUserName = "MODERATOR",
                            PasswordHash = "4c8425b174053ea6935b29c2b0e0aa4e2eab1a01b784e6ac91b8bdce9c26235a",
                            PhoneNumberConfirmed = false,
                            Post = "Модератор",
                            SecurityStamp = "security-3",
                            TwoFactorEnabled = false,
                            UserName = "moderator"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ApprovalStatus = "Approved",
                            ConcurrencyStamp = "user-4",
                            EmailConfirmed = false,
                            FullName = "Козлова Мария Ивановна",
                            LockoutEnabled = true,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            PhoneNumberConfirmed = false,
                            Post = "Администратор",
                            SecurityStamp = "security-4",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rc_role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uc_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ul_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ur_role");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ur_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ut_user");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.ApproverAssignment", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "ApproverUser")
                        .WithMany("ApproverAssignments")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appr_user");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appr_by");

                    b.HasOne("PersonalCabinetEducationProgram.Models.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_appr_dept");

                    b.HasOne("PersonalCabinetEducationProgram.Models.Facultys", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_appr_fac");

                    b.Navigation("ApproverUser");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Department");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgram", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("EducationalPrograms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_prog_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramAssignment", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epa_dept");

                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("Assignments")
                        .HasForeignKey("EducationalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epa_prog");

                    b.HasOne("PersonalCabinetEducationProgram.Models.Facultys", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epa_fac");

                    b.Navigation("Department");

                    b.Navigation("EducationalProgram");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElement", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("Elements")
                        .HasForeignKey("EducationalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_elem_prog");

                    b.Navigation("EducationalProgram");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElementComment", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgramElement", "Element")
                        .WithMany("Comments")
                        .HasForeignKey("EducationalProgramElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comm_elem");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comm_user");

                    b.Navigation("Element");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramManager", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mgr_by");

                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgram", "EducationalProgram")
                        .WithMany("Managers")
                        .HasForeignKey("EducationalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mgr_prog");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany("EducationalProgramManagers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mgr_user");

                    b.Navigation("AssignedByUser");

                    b.Navigation("EducationalProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.ElementStatusHistory", b =>
                {
                    b.HasOne("PersonalCabinetEducationProgram.Models.EducationalProgramElement", "Element")
                        .WithMany()
                        .HasForeignKey("EducationalProgramElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hist_elem");

                    b.HasOne("PersonalCabinetEducationProgram.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hist_user");

                    b.Navigation("Element");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgram", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Elements");

                    b.Navigation("Managers");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.EducationalProgramElement", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PersonalCabinetEducationProgram.Models.User", b =>
                {
                    b.Navigation("ApproverAssignments");

                    b.Navigation("Comments");

                    b.Navigation("EducationalProgramManagers");

                    b.Navigation("EducationalPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
